# Please see the documentation for all configuration options: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # github-actions
  - directory: "/"
    package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
      # Use America/New_York Standard Time (UTC -05:00)
      timezone: "America/New_York"
    groups:
      all-github-actions:
        patterns: [ "*" ]
    commit-message:
      prefix: "dependabot"
      include: scope
    labels:
      - "ok-to-test"
      - "kind/cleanup"
      - "release-note-none"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      # Use America/New_York Standard Time (UTC -05:00)
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "dependabot"
      include: scope
    ignore:
      - dependency-name: 'golang'
    labels:
      - "ok-to-test"
      - "kind/cleanup"
      - "release-note-none"

  # pip
  - package-ecosystem: "pip"
    directories:
        - "/"
        - "images/capi"
    schedule:
      interval: "weekly"
      time: "09:00"
      # Use America/New_York Standard Time (UTC -05:00)
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "dependabot"
      include: scope
    labels:
      - "ok-to-test"
      - "kind/cleanup"
      - "release-note-none"
