# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
options:
  substitution_option: ALLOW_LOOSE
steps:
  # 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211008-60e346af'
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud@sha256:67925b5897028eaab9a481c4ee9df00ab58d02e24103dfd1fe34cff81d9d0fb9'
    entrypoint: make
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
      - DOCKER_BUILDKIT=1
    args: ['-C', 'images/capi', 'release-staging']
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
