# Copyright 2024 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Upgrade pip to latest
  ansible.builtin.pip: # noqa package-latest
    name: pip
    executable: pip3
    state: latest
  when: ansible_os_family == "Debian"

- name: Uninstall cloud-init pip package
  ansible.builtin.pip:
    name: "cloud-init"
    executable: pip3
    state: absent
  when: ansible_os_family == "Debian"

- name: Create dns default conf directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"
  when: ansible_os_family == "Debian"

- name: Add default dns
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/default.conf
    content: |-
      [Resolve]
      DNS=8.8.8.8
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Debian"
