# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Bootstrap Python
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if Python is installed
      changed_when: false
      failed_when: false
      ansible.builtin.raw: test -e "{{ ansible_python_interpreter | default('/usr/bin/python3') }}"
      register: python_installed

    - name: Install Python
      changed_when: true
      ansible.builtin.raw: test -e /usr/bin/apt && (apt-get update && apt-get install -y python3) || (yum install -y python3)
      when: python_installed.rc != 0

- hosts: all
  become: true
  vars:
    firstboot_custom_roles_pre: ""
    firstboot_custom_roles_post: ""

  tasks:
    - ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ firstboot_custom_roles_pre.split() }}"
      loop_control:
        loop_var: role
      when: firstboot_custom_roles_pre != ""
    - ansible.builtin.include_role:
        name: kubernetes_sigs.image_builder.firstboot
    - ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ firstboot_custom_roles_post.split() }}"
      loop_control:
        loop_var: role
      when: firstboot_custom_roles_post != ""

  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    HTTP_PROXY: "{{ http_proxy | default('') }}"
    HTTPS_PROXY: "{{ https_proxy | default('') }}"
    NO_PROXY: "{{ no_proxy | default('') }}"
