# Required pipeline variables:
# - BUILD_POOL - Azure DevOps build pool to use
# - CONTAINER_IMAGE - Dev container image URL to use. Should have Azure CLI, Packer and Ansible.
# - AZURE_TENANT_ID_VHD - tenant ID to build the vhd
# - AZURE_CLIENT_ID_VHD - Service principal ID to build the vhd
# - AZURE_CLIENT_SECRET_VHD - Service principal secret to build the vhd
# - AZURE_SUBSCRIPTION_ID_VHD - Subscription ID to build the vhd
# - AZURE_TENANT_ID_SKU - tenant ID to PUT the SKU
# - AZURE_CLIENT_ID_SKU - Service principal ID to PUT the SKU
# - AZURE_CLIENT_SECRET_SKU - Service principal secret to PUT the SKU
# - KUBERNETES_VERSION - version of Kubernetes to create the sku for, e.g. `1.16.2`
# - PUBLISHER - the name of the publisher to create the sku for
# - OFFER - the name of the offer to create the sku for
# - SKU_TEMPLATE_FILE - the base template file to use for the sku
# - OS - target of build e.g. `Ubuntu/Windows`
# - OS_VERSION - target of build e.g. `18.04/2004/2019`

trigger: none
pr: none

stages:
  - stage: vhd
    jobs:
    - template: build-vhd.yaml
    variables:
      AZURE_TENANT_ID: $(AZURE_TENANT_ID_VHD)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID_VHD)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET_VHD)
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID_VHD)

  - stage: sku
    condition: and(succeeded(), eq(variables.CLEANUP, 'False'))
    jobs:
    - template: create-sku.yaml
    variables:
      AZURE_TENANT_ID: $(AZURE_TENANT_ID_SKU)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID_SKU)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET_SKU)

  - stage: disk_version
    condition: and(succeeded(), eq(variables.CLEANUP, 'False'))
    jobs:
    - template: create-disk-version.yaml
    variables:
      AZURE_TENANT_ID: $(AZURE_TENANT_ID_SKU)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID_SKU)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET_SKU)
