# Required pipeline variables:
# - BUILD_POOL - Azure DevOps build pool to use
# - KUBERNETES_VERSION - version of Kubernetes to build the image with, e.g. `1.31.1`
# - OFFER - the name of the offer to create the sku for
# - OS - target of build, one of `Ubuntu` or `Windows`
# - OS_VERSION - target of build, one of `24.04`, `22.04`, `2022-containerd`, or `2019-containerd`
# - PUBLISHER - the name of the publisher to create the sku for
# - RESOURCE_GROUP - name of the Azure resource group to use for the Compute galleries
# - SERVICE_CONNECTION - Azure DevOps service connection to use for the Azure CLI
# - STAGING_GALLERY_NAME - name of the Azure Compute Gallery for initial image publishing

trigger: none
pr: none

stages:
  - stage: build
    jobs:
    - template: build-sig.yaml

  - stage: test
    condition: not(always()) # skip for now
    jobs:
    - template: test-sig.yaml

  - stage: promote
    condition: not(or(failed(), canceled()))
    jobs:
    - template: promote-sig.yaml

  - stage: clean
    condition: always()
    jobs:
    - template: clean-sig.yaml
