# Copyright 2023 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Define file modes
  set_fact:
    last_log_mode:   "0644"
    machine_id_mode: "0444"

- name: Get installed packages
  package_facts:

- name: Create the package list
  set_fact:
    package_list: "{{ ansible_facts.packages.keys() | join(' ') }}"

- import_tasks: rpm_repos.yml

- name: Ensure nftables config ends with a newline
  shell: /bin/echo "" >> /etc/sysconfig/nftables.conf

- name: Disable swap service and ensure it is masked
  systemd:
    name: swap.target
    enabled: no
    masked: yes
  when: ansible_memory_mb.swap.total != 0

- name: Remove the kickstart log
  file:
    state: absent
    path: /root/anaconda-ks.cfg
