# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
debug_files:
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/collectlogs.ps1
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/dumpVfpPolicies.ps1
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/portReservationTest.ps1
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/starthnstrace.cmd
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/startpacketcapture.cmd
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/startpacketcapture.ps1
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/stoppacketcapture.cmd
  - https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/debug/VFP.psm1
  - https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/helper.psm1
  - https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/hns.psm1
  - https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hack/DebugWindowsNode.ps1

additional_debug_files_list: "{{ additional_debug_files.split(',') if (additional_debug_files is defined) and (additional_debug_files | length > 0) else [] }}"
