- name: Disable module
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/disable-{{ item }}.conf"
    content: |
      install {{ item }} /bin/false
  loop: "{{ disabled_kernel_modules }}"

- name: Remove module if currently loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ disabled_kernel_modules }}"
