$DriveLetter = "M"
$Label = "cidata"
$metadata = "meta-data"
$userdata = "user-data"
$metadataPath = "${DriveLetter}:\${metadata}"
$userdataPath = "${DriveLetter}:\${userdata}"
$logfile = "$env:SystemDrive\logs\configure-k8s.log"

# Find the first uninitialized disk
$UninitializedDisk = $null
$RetryCount = 0
$MaxRetries = 5
$BackoffSeconds = 10

while (-not $UninitializedDisk -and $RetryCount -lt $MaxRetries) {
    $UninitializedDisk = Get-Disk | Where-Object PartitionStyle -EQ "Raw" | Select-Object -First 1
    if (-not $UninitializedDisk) {
        $RetryCount++
        $backoff = ($BackoffSeconds * $RetryCount)
        $LogMessage = "Disk not found;  attempts: $RetryCount; trying again after $backoff seconds"
        $LogMessage | Out-File -FilePath $logfile  -Append -Encoding UTF8 
        Start-Sleep -Seconds $backoff
    }
}

if ($UninitializedDisk) {
    $DiskNumber = $UninitializedDisk.Number

    Initialize-Disk -Number $DiskNumber -PartitionStyle MBR
    $Partition = New-Partition -DiskNumber $DiskNumber -UseMaximumSize -AssignDriveLetter
    Format-Volume -DriveLetter $Partition.DriveLetter -FileSystem FAT32 -NewFileSystemLabel $Label -Confirm:$false
    Set-Partition -DriveLetter $Partition.DriveLetter -NewDriveLetter $DriveLetter

    # Create a YAML file with the hostname which was already configured via Azure Provisioner
    # Valid yaml file is required to set up the NoCloud service otherwise the service instantiation won't work
    # setting local-hostname allows for the use of instance metadata in CAPZ in the format "ds.meta_data["local_hostname"]"
    # which is generated by a CAPI component for the kubeadm JoinConfiguration
    # https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html  
    # https://github.com/cloudbase/cloudbase-init/blob/aa06aeeecdb42053d09e48d00647dce3439009ec/cloudbaseinit/metadata/services/nocloudservice.py#L578
    $Hostname = $env:COMPUTERNAME
    "local-hostname: $Hostname" | Out-File -Encoding ASCII -FilePath $metadataPath

    # move the custom data that was provisioned via Azure to the drive so cloud base can process it
    cp $env:SystemDrive\AzureData\CustomData.bin $userdataPath
    icacls $userdataPath /inheritance:r /grant:r  --% *S-1-5-18:(OI)(CI)F *S-1-5-32-544:(OI)(CI)F
    icacls $metadataPath /inheritance:r /grant:r  --% *S-1-5-18:(OI)(CI)F *S-1-5-32-544:(OI)(CI)F

    "Formatted and configured disk $DiskNumber as $DriveLetter with $Label. Starting Cloudbase init" | Out-File -FilePath $logfile  -Append -Encoding UTF8 
    cmd /c "sc config cloudbase-init start= auto && net start cloudbase-init"
    "Cloudbase-init running" | Out-File -FilePath $logfile  -Append -Encoding UTF8 
    Disable-ScheduledTask -TaskName "configure-k8s"
    "Disabled scheduled Task" | Out-File -FilePath $logfile  -Append -Encoding UTF8 
} else {
    "No uninitialized disks found. Cloudbase-init may not run" | Out-File -FilePath $logfile -Append -Encoding UTF8
    throw "No uninitialized disks were found after $MaxRetries attempts. Exiting script."
}
